"""Generate the web assets from palette.py (standard library only).

    python brand/build.py

Writes, next to this file:
    tokens.json        every value, for any tool that reads JSON
    css/brand.css      CSS variables (light + dark) and a few components
    js/palette.js      ES module for charts in the browser
    icons/*.svg        app tiles, mark-only icons, and favicons

PNG images (favicons, README banners, social previews) come from render.py,
which needs Playwright. Re-run both after changing palette.py.
"""

from __future__ import annotations

import json
from pathlib import Path

import palette as p

HERE = Path(__file__).resolve().parent
HEADER = "Generated by brand/build.py from brand/palette.py. Do not edit by hand."


# --------------------------------------------------------------------------- css
def _mode_block(mode: str, indent: str = "  ") -> str:
    s = p.SURFACE[mode]
    lines = [f"color-scheme: {mode};"]
    lines += [f"--{k.replace('_', '-')}: {v};" for k, v in s.items()]
    lines += [f"--c-{k}: {v};" for k, v in p.SERIES[mode].items()]
    lines += [f"--accent-{a}: {p.ACCENT_TEXT[mode][a]};" for a in p.APPS]
    lines += [f"--status-{k}: {v};" for k, v in p.STATUS[mode].items()]
    lines += [f"--status-{k}-text: {v};" for k, v in p.STATUS_TEXT[mode].items()]
    lines += [f"--div-{i + 1}: {c};" for i, c in enumerate(p.DIVERGING[mode])]
    return "\n".join(indent + line for line in lines)


def _app_block(app: str) -> str:
    lines = [f"  --brand-fill: {p.BRAND_FILL[app]};", f"  --accent: var(--accent-{app});"]
    lines += [f"  --series-{i + 1}: var(--c-{k});" for i, k in enumerate(p.SERIES_ORDER[app])]
    lines += [f"  --seq-{i + 1}: {c};" for i, c in enumerate(p.SEQUENTIAL[app])]
    return "\n".join(lines)


def build_css() -> str:
    dark, light, light_nested = _mode_block("dark"), _mode_block("light"), _mode_block("light", "    ")
    apps = "\n\n".join(f'[data-app="{a}"] {{\n{_app_block(a)}\n}}' for a in p.APPS)
    return f"""/* {HEADER} */
@import url("{p.FONTS['google_css']}");

/* ---- Tokens: dark is the default; light follows the OS unless the page
   sets data-theme="dark" or data-theme="light" on <html>. ---- */
:root {{
{dark}
  --on-brand-fill: {p.ON_BRAND_FILL};
  --core-outline: {p.CORE_OUTLINE};
  --font-sans: {p.FONTS['sans']};
  --font-mono: {p.FONTS['mono']};
}}

@media (prefers-color-scheme: light) {{
  :root:not([data-theme="dark"]) {{
{light_nested}
  }}
}}

:root[data-theme="light"] {{
{light}
}}

/* ---- Per-app colors: put data-app="tps" | "roi" | "valuation" on <html>. ---- */
{apps}

/* ---- Base ---- */
*, *::before, *::after {{ box-sizing: border-box; }}
body {{
  margin: 0;
  background: var(--page);
  color: var(--ink);
  font-family: var(--font-sans);
  line-height: 1.5;
}}
a {{ color: var(--accent); }}
a:hover {{ color: var(--ink); }}
code, pre, .num {{ font-family: var(--font-mono); }}
.num {{ font-variant-numeric: tabular-nums; }}
.muted {{ color: var(--ink-secondary); }}

/* ---- Header: icon tile, name, question, endorsement ---- */
.brand-header {{
  border-top: 6px solid var(--brand-fill);
  background: var(--panel);
  border-bottom: 1px solid var(--line);
}}
.brand-header__inner {{
  max-width: 1120px;
  margin: 0 auto;
  padding: 20px 16px;
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 12px 16px;
}}
.brand-tile {{
  width: 48px;
  height: 48px;
  flex-shrink: 0;
  background: var(--brand-fill);
  color: var(--on-brand-fill);
  display: grid;
  place-items: center;
}}
.brand-tile svg {{ width: 30px; height: 30px; }}
.brand-header__text {{ display: flex; flex-direction: column; gap: 2px; min-width: 0; flex: 1 1 280px; }}
.brand-header__name {{ margin: 0; font-size: 1.5rem; font-weight: 700; line-height: 1.2; }}
.brand-header__question {{ margin: 0; font-size: 1rem; font-weight: 500; }}
.brand-header__by {{ font-size: 0.875rem; color: var(--ink-secondary); }}

/* ---- Cards and footer ---- */
.brand-card {{ background: var(--panel); border: 1px solid var(--line); padding: 20px; }}
.brand-footer {{
  max-width: 1120px;
  margin: 48px auto 0;
  padding: 16px;
  border-top: 1px solid var(--line);
  font-size: 0.75rem;
  color: var(--ink-secondary);
}}

/* ---- Status: reserved meaning, always icon + label ---- */
.status {{
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 2px 10px;
  border: 1px solid currentColor;
  font-size: 0.875rem;
  font-weight: 500;
}}
.status--good {{ color: var(--status-good-text); }}
.status--good::before {{ content: "\\2713"; }}
.status--warning {{ color: var(--status-warning-text); }}
.status--warning::before {{ content: "!"; font-weight: 700; }}
.status--critical {{ color: var(--status-critical-text); }}
.status--critical::before {{ content: "\\2715"; }}
"""


# ---------------------------------------------------------------------------- js
def build_js() -> str:
    data = json.dumps(p.all_tokens(), indent=2, ensure_ascii=False)
    return f"""// {HEADER}
// Usage:
//   import {{ series, currentMode, plotlyLayout }} from "./brand/js/palette.js";
//   const colors = series("tps");          // slot 1 = the app's own color
//   Plotly.newPlot(el, data, plotlyLayout("tps"));

export const tokens = {data};

/** "dark" or "light", honoring data-theme on <html>, then the OS setting. */
export function currentMode() {{
  const forced = document.documentElement.dataset.theme;
  if (forced === "dark" || forced === "light") return forced;
  return window.matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark";
}}

/** Chart colors for n series (max {p.MAX_SERIES}). Slot 1 is the app's own color. */
export function series(app, mode = currentMode(), n = tokens.maxSeries) {{
  if (n < 1 || n > tokens.maxSeries) {{
    throw new Error(`${{n}} series requested; max is ${{tokens.maxSeries}}. Fold the rest into "Other" or use small multiples.`);
  }}
  return tokens.apps[app].seriesOrder.slice(0, n).map((k) => tokens.series[mode][k]);
}}

/** Low -> high magnitude ramp in the app's hue. In dark mode, low sits near the surface. */
export function sequential(app, mode = currentMode()) {{
  const ramp = [...tokens.apps[app].sequential];
  return mode === "dark" ? ramp.reverse() : ramp;
}}

export const diverging = (mode = currentMode()) => [...tokens.diverging[mode]];
export const status = (mode = currentMode()) => ({{ ...tokens.status[mode] }});
export const surface = (mode = currentMode()) => ({{ ...tokens.surface[mode] }});

/** Re-run a chart's draw function when the color mode changes. */
export function onModeChange(callback) {{
  const mq = window.matchMedia("(prefers-color-scheme: light)");
  const fire = () => callback(currentMode());
  mq.addEventListener("change", fire);
  new MutationObserver(fire).observe(document.documentElement, {{ attributes: true, attributeFilter: ["data-theme"] }});
}}

/** A Plotly.js layout with this app's colors. Merge your own settings on top. */
export function plotlyLayout(app, mode = currentMode()) {{
  const s = tokens.surface[mode];
  const axis = {{
    gridcolor: s.line, linecolor: s.line, zerolinecolor: s.line,
    tickfont: {{ color: s.ink_muted }}, title: {{ font: {{ color: s.ink_secondary }} }},
  }};
  return {{
    colorway: series(app, mode),
    paper_bgcolor: s.page,
    plot_bgcolor: s.page,
    font: {{ family: "Space Grotesk, system-ui, sans-serif", color: s.ink }},
    xaxis: axis,
    yaxis: axis,
    legend: {{ font: {{ color: s.ink_secondary }} }},
    hoverlabel: {{ bgcolor: s.panel, bordercolor: s.line, font: {{ color: s.ink }} }},
  }};
}}
"""


# ------------------------------------------------------------------------- icons
def _svg(inner: str, size: int = 64) -> str:
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" '
            f'viewBox="0 0 64 64">{inner}</svg>\n')


def _strokes(key: str, color: str, transform: str = "") -> str:
    t = f' transform="{transform}"' if transform else ""
    return (f'<g fill="none" stroke="{color}" color="{color}" stroke-width="4" '
            f'stroke-linecap="round" stroke-linejoin="round"{t}>{p.ICON_PATHS[key]}</g>')


def build_icons() -> dict[str, str]:
    out: dict[str, str] = {}
    shrink = "translate(9.6 9.6) scale(0.7)"  # mark at 70% inside the tile
    for app in p.APPS:
        tile = f'<rect width="64" height="64" fill="{p.BRAND_FILL[app]}"/>' + _strokes(app, p.ON_BRAND_FILL, shrink)
        out[f"{app}.svg"] = _svg(tile)
        out[f"{app}-mark.svg"] = _svg(_strokes(app, "currentColor"))
    core_tile = (f'<rect x="1.5" y="1.5" width="61" height="61" fill="{p.SURFACE["dark"]["panel"]}" '
                 f'stroke="{p.CORE_OUTLINE}" stroke-width="3"/>' + _strokes("core", p.SURFACE["dark"]["ink"], shrink))
    out["core.svg"] = _svg(core_tile)
    out["core-mark.svg"] = _svg(_strokes("core", "currentColor"))
    return out


def main() -> None:
    (HERE / "css").mkdir(exist_ok=True)
    (HERE / "js").mkdir(exist_ok=True)
    (HERE / "icons").mkdir(exist_ok=True)
    (HERE / "tokens.json").write_text(json.dumps(p.all_tokens(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (HERE / "css" / "brand.css").write_text(build_css(), encoding="utf-8")
    (HERE / "js" / "palette.js").write_text(build_js(), encoding="utf-8")
    for name, svg in build_icons().items():
        (HERE / "icons" / name).write_text(svg, encoding="utf-8")
    print("Wrote tokens.json, css/brand.css, js/palette.js and", len(build_icons()), "icons.")


if __name__ == "__main__":
    main()
